const kinksData = {
    "BDSM & Domination": [
        "Bondage (léger)",
        "Bondage (strict)",
        "Shibari/Kinbaku",
        "Menottes",
        "Chaînes",
        "Corde",
        "Ruban adhésif",
        "Bandeau sur les yeux",
        "Bâillon",
        "Privation sensorielle",
        "Domination",
        "Soumission",
        "Switch (alternance Dom/Sub)",
        "Maître/Maîtresse et esclave",
        "Propriété/Ownership",
        "Discipline",
        "Punition",
        "Récompenses",
        "Ordres/Commandements",
        "Rituels",
        "Protocoles",
        "Service domestique",
        "Pet play (jeu d'animal)",
        "Pony play",
        "Puppy play",
        "Kitten play",
        "Primal play",
        "Chasse prédateur/proie",
        "Lutte/Wrestling"
    ],
    "Impact Play": [
        "Fessée (main)",
        "Paddle",
        "Cravache",
        "Fouet",
        "Martinet",
        "Canne",
        "Flogger",
        "Crop",
        "Impact léger",
        "Impact modéré",
        "Impact intense",
        "Marques temporaires",
        "Marques durables",
        "Ecchymoses"
    ],
    "Sensation & Température": [
        "Plumes",
        "Glace",
        "Cire chaude",
        "Jeu de température",
        "Roue de Wartenberg",
        "Pinces à tétons",
        "Pinces à tétons avec poids",
        "Pompe à tétons",
        "Pompe à clitoris",
        "Pompe à vulve",
        "Électrostimulation",
        "Vibrations",
        "Chatouilles",
        "Griffures",
        "Morsures",
        "Succion/Hickeys"
    ],
    "Oral & Pénétration": [
        "Cunnilingus",
        "Fellation",
        "Anulingus",
        "Gorge profonde",
        "Facesitting",
        "Pénétration vaginale",
        "Pénétration anale",
        "Double pénétration",
        "Fisting vaginal",
        "Fisting anal",
        "Godes",
        "Plugs anaux",
        "Perles anales",
        "Gros jouets",
        "Petits jouets",
        "Vibromasseurs",
        "Jouets télécommandés",
        "Gode ceinture (strap-on)",
        "Pegging",
        "Dilatation",
        "Speculums"
    ],
    "Fluides & Liquides": [
        "Éjaculation faciale",
        "Éjaculation buccale",
        "Éjaculation sur le corps",
        "Éjaculation interne",
        "Avaler",
        "Cracher",
        "Squirt/Éjaculation féminine",
        "Golden shower (donner)",
        "Golden shower (recevoir)",
        "Jeux d'urine",
        "Salive/Crachat",
        "Lactation",
        "Scat (donner)",
        "Scat (recevoir)",
        "Énurésie/Omorashi",
        "Wetlook"
    ],
    "Sexe en Public & Exhibition": [
        "Sexe en public",
        "Exhibition",
        "Voyeurisme",
        "Être regardé(e)",
        "Regarder les autres",
        "Dogging",
        "Nudité en public",
        "Upskirt",
        "Partouze/Orgie",
        "Gang bang",
        "Gloryhole",
        "Sex clubs",
        "Sex parties",
        "Webcam",
        "Contenu pornographique amateur",
        "Photos/Vidéos (de soi)",
        "Photos/Vidéos (de son/sa partenaire)"
    ],
    "Roleplay & Fantasmes": [
        "Jeu de rôle",
        "Âgeplay (adulte/adulte)",
        "Daddy/Mommy Dom",
        "Little/Middle",
        "Inceste (roleplay)",
        "Médecin/Patient",
        "Enseignant/Élève",
        "Patron/Employé",
        "Uniforme (militaire)",
        "Uniforme (police)",
        "Uniforme (infirmière)",
        "Cosplay",
        "Furry",
        "Fantasy (elfes, etc.)",
        "Alien/Monstre",
        "Viol consensuel (CNC)",
        "Kidnapping (roleplay)",
        "Interrogatoire",
        "Blackmail (roleplay)"
    ],
    "Partenaires Multiples": [
        "Trio (FFM)",
        "Trio (MMF)",
        "Trio (FFF)",
        "Trio (MMM)",
        "Échangisme",
        "Candaulisme",
        "Hotwifing",
        "Cuckolding",
        "Polyamour",
        "Relation ouverte",
        "Gang bang (recevoir)",
        "Gang bang (participer)",
        "Bukkake",
        "Orgies"
    ],
    "Fétichisme": [
        "Pieds",
        "Chaussures",
        "Talons hauts",
        "Bottes",
        "Bas/Collants",
        "Lingerie",
        "Cuir",
        "Latex",
        "PVC",
        "Satin/Soie",
        "Fourrure",
        "Caoutchouc",
        "Spandex/Lycra",
        "Corsets",
        "Culottes/Strings",
        "Soutiens-gorge",
        "Body",
        "Porte-jarretelles",
        "Masques",
        "Gants",
        "Muscles",
        "Poils corporels",
        "Rasé(e) complètement",
        "Tatouages",
        "Piercings",
        "Lunettes",
        "Cheveux longs",
        "Cheveux courts",
        "Odeurs corporelles",
        "Parfum/Cologne",
        "Sueur",
        "Aisselles"
    ],
    "Humiliation & Dégradation": [
        "Humiliation verbale",
        "Dirty talk",
        "Insultes",
        "Traitement d'objet",
        "Humiliation publique",
        "Humiliation privée",
        "Être ignoré(e)",
        "Servir de cendrier humain",
        "Servir de meuble humain",
        "Léchage de chaussures",
        "Adoration",
        "Adoration des pieds",
        "Adoration du corps",
        "Féminisation",
        "Masculinisation",
        "Sissification",
        "Travestissement forcé",
        "Chastété",
        "Cage de chasteté",
        "Déni d'orgasme",
        "Orgasmes forcés",
        "Ruined orgasm",
        "Edging/Orgasm control"
    ],
    "Jeu Mental & Psychologique": [
        "Mind games",
        "Manipulation consensuelle",
        "Gaslighting (roleplay)",
        "Hypnose érotique",
        "Contrôle mental (fantasy)",
        "Lavage de cerveau (roleplay)",
        "Méditation érotique",
        "Conditionnement",
        "Triggers",
        "Mantras",
        "Journalisation",
        "Tâches/Devoirs",
        "Attente/Anticipation",
        "Surprise",
        "Spontanéité",
        "Planification détaillée"
    ],
    "Médical & Body Mod": [
        "Medical play",
        "Examens médicaux (roleplay)",
        "Cathéters",
        "Sondes",
        "Lavements",
        "Injections (roleplay)",
        "Aiguilles/Needleplay",
        "Cutting (légère scarification)",
        "Branding",
        "Piercing temporaire",
        "Piercing permanent",
        "Tatouages temporaires",
        "Tatouages permanents",
        "Modification corporelle",
        "Pompage/Pumping",
        "Expansion",
        "Vacuum play"
    ],
    "Restrictions & Contrôle": [
        "Contrôle de l'alimentation",
        "Contrôle vestimentaire",
        "Contrôle des sorties",
        "Contrôle financier (roleplay)",
        "Contrôle des relations sociales",
        "Contrat BDSM",
        "Règles et protocoles",
        "Suivi/Surveillance",
        "Collier/Symbole de propriété",
        "Cage/Enfermement",
        "Isolation",
        "Sleep deprivation (consensuel)",
        "Jeûne (supervisé)",
        "Restrictions de parole",
        "Forced silence"
    ],
    "Romance & Intimité": [
        "Câlins",
        "Baisers",
        "Baisers profonds",
        "Massage sensuel",
        "Massage érotique",
        "Caresses",
        "Aftercare intense",
        "Mots doux",
        "Louanges/Praise",
        "Romance classique",
        "Dîner aux chandelles",
        "Eye contact prolongé",
        "Slow sex",
        "Tantrique",
        "Connexion spirituelle",
        "Making love vs. fucking",
        "Sommeil ensemble",
        "Bain ensemble",
        "Se laver mutuellement"
    ],
    "Extrême & Edge Play": [
        "Breath play",
        "Choking",
        "Asphyxiation",
        "Blood play",
        "Knife play",
        "Gun play (jouet)",
        "Fear play",
        "Extreme pain",
        "Suspension",
        "Mummification",
        "Vacuum beds",
        "Intoxication play",
        "Edge play général"
    ],
    "Technologie & Moderne": [
        "Sexting",
        "Sexe au téléphone",
        "Sexe par vidéo",
        "Contrôle à distance (jouets)",
        "Porn watching together",
        "Hentai/Anime porn",
        "Audio porn",
        "Literotica",
        "VR porn",
        "Sex robots/dolls",
        "Applications de rencontre",
        "OnlyFans/Contenu adulte",
        "Streaming adulte"
    ],
    "Situations & Contextes": [
        "Sexe matinal",
        "Sexe avant de dormir",
        "Quickie",
        "Sexe marathon",
        "Sexe sous la douche",
        "Sexe dans le bain",
        "Sexe en voiture",
        "Sexe en nature",
        "Sexe à l'hôtel",
        "Sexe au travail (fantaisie)",
        "Sexe pendant les règles",
        "Sexe pendant la grossesse",
        "Sexe avec de la musique",
        "Sexe en silence",
        "Sexe ivre/high",
        "Sexe sobre uniquement"
    ],
    "Communication & Consentement": [
        "Safe words",
        "Check-ins réguliers",
        "Négociation avant",
        "Débriefing après",
        "Communication non-verbale",
        "Signaux",
        "Hard limits respectés",
        "Soft limits explorés",
        "Négociation continue",
        "Consentement enthousiaste",
        "Consentement informed",
        "Discussion des limites",
        "Partage de fantasmes",
        "Journalisation partagée"
    ]
};
