const kinksData = {
    "BDSM général & Domination": [
        "Bondage (léger)",
        "Bondage (strict)",
        "Shibari/Kinbaku",
        "Menottes",
        "Chaînes",
        "Corde",
        "Ruban adhésif",
        "Bandeau sur les yeux",
        "Bâillon",
        "Privation sensorielle",
        "Domination",
        "Soumission",
        "Switch (alternance Dom/Sub)",
        "Maître/Maîtresse et esclave",
        "Propriété/Ownership",
        "Discipline",
        "Punition",
        "Récompenses",
        "Ordres/Commandements",
        "Rituels",
        "Protocoles",
        "Service domestique",
        "Pet play (jeu d'animal)",
        "Pony play",
        "Puppy play",
        "Kitten play",
        "Primal play",
        "Chasse prédateur/proie",
        "Lutte/Wrestling"
    ],
    "Impact Play - Outils & Intensité": [
        "Fessée (main)",
        "Paddle",
        "Cravache",
        "Fouet",
        "Martinet",
        "Canne",
        "Flogger",
        "Crop",
        "Impact léger",
        "Impact modéré",
        "Impact intense",
        "Marques temporaires",
        "Marques durables",
        "Ecchymoses"
    ],
    "Sensations - Température & Corps": [
        "Plumes",
        "Glace",
        "Cire chaude",
        "Jeu de température",
        "Roue de Wartenberg",
        "Pinces à tétons",
        "Pinces à tétons avec poids",
        "Pompe à tétons",
        "Pompe à clitoris",
        "Pompe à vulve",
        "Électrostimulation",
        "Vibrations",
        "Chatouilles",
        "Griffures",
        "Morsures",
        "Succion/Hickeys"
    ],
    "Oral, Pénétration & Jouets classiques": [
        "Cunnilingus",
        "Fellation",
        "Anulingus",
        "Gorge profonde",
        "Facesitting",
        "Pénétration vaginale",
        "Pénétration anale",
        "Double pénétration",
        "Fisting vaginal",
        "Fisting anal",
        "Godes",
        "Plugs anaux",
        "Perles anales",
        "Gros jouets",
        "Petits jouets",
        "Vibromasseurs",
        "Jouets télécommandés",
        "Gode ceinture (strap-on)",
        "Pegging",
        "Dilatation",
        "Speculums"
    ],
    "Fluides corporels": [
        "Éjaculation faciale",
        "Éjaculation buccale",
        "Éjaculation sur le corps",
        "Éjaculation interne",
        "Avaler",
        "Cracher",
        "Squirt/Éjaculation féminine",
        "Golden shower",
        "Jeux d'urine",
        "Salive/Crachat",
        "Lactation",
        "Scat",
        "Énurésie/Omorashi",
        "Wetlook"
    ],
    "Lieux publics, Clubs & Exhibition": [
        "Sexe en public",
        "Exhibition",
        "Voyeurisme",
        "Être regardé(e)",
        "Regarder les autres",
        "Dogging",
        "Nudité en public",
        "Upskirt",
        "Partouze/Orgie",
        "Gang bang",
        "Gloryhole",
        "Sex clubs",
        "Sex parties",
        "Webcam",
        "Contenu pornographique amateur",
        "Photos/Vidéos (de soi)",
        "Photos/Vidéos (de son/sa partenaire)"
    ],
    "Roleplay - Archétypes classiques": [
        "Jeu de rôle",
        "Âgeplay (adulte/adulte)",
        "Daddy/Mommy Dom",
        "Little/Middle",
        "Inceste (roleplay)",
        "Médecin/Patient",
        "Enseignant/Élève",
        "Patron/Employé",
        "Uniforme (militaire)",
        "Uniforme (police)",
        "Uniforme (infirmière)",
        "Cosplay",
        "Furry",
        "Fantasy (elfes, etc.)",
        "Alien/Monstre",
        "Viol consensuel (CNC)",
        "Kidnapping (roleplay)",
        "Interrogatoire",
        "Blackmail (roleplay)"
    ],
    "Partenaires multiples - Pratiques classiques": [
        "Trio (FFM)",
        "Trio (MMF)",
        "Trio (FFF)",
        "Trio (MMM)",
        "Échangisme",
        "Candaulisme",
        "Hotwifing",
        "Cuckolding",
        "Polyamour",
        "Relation ouverte",
        "Bukkake",
        "Orgies"
    ],
    "Fétichisme": [
        "Pieds",
        "Chaussures",
        "Talons hauts",
        "Bottes",
        "Bas/Collants",
        "Lingerie",
        "Cuir",
        "Latex",
        "PVC",
        "Satin/Soie",
        "Fourrure",
        "Caoutchouc",
        "Spandex/Lycra",
        "Corsets",
        "Culottes/Strings",
        "Soutiens-gorge",
        "Body",
        "Porte-jarretelles",
        "Masques",
        "Gants",
        "Muscles",
        "Poils corporels",
        "Rasé(e) complètement",
        "Tatouages",
        "Piercings",
        "Lunettes",
        "Cheveux longs",
        "Cheveux courts",
        "Odeurs corporelles",
        "Parfum/Cologne",
        "Sueur",
        "Aisselles"
    ],
    "Humiliation, Dégradation & Contrôle sexuel": [
        "Humiliation verbale",
        "Dirty talk",
        "Insultes",
        "Traitement d'objet",
        "Humiliation publique",
        "Humiliation privée",
        "Être ignoré(e)",
        "Servir de cendrier humain",
        "Servir de meuble humain",
        "Léchage de chaussures",
        "Adoration",
        "Adoration des pieds",
        "Adoration du corps",
        "Féminisation",
        "Masculinisation",
        "Sissification",
        "Travestissement forcé",
        "Chastété",
        "Cage de chasteté",
        "Déni d'orgasme",
        "Orgasmes forcés",
        "Ruined orgasm",
        "Edging/Orgasm control"
    ],
    "Jeu Mental & Psychologique": [
        "Mind games",
        "Manipulation consensuelle",
        "Gaslighting (roleplay)",
        "Hypnose érotique",
        "Contrôle mental (fantasy)",
        "Lavage de cerveau (roleplay)",
        "Méditation érotique",
        "Conditionnement",
        "Triggers",
        "Mantras",
        "Journalisation",
        "Tâches/Devoirs",
        "Attente/Anticipation",
        "Surprise",
        "Spontanéité",
        "Planification détaillée"
    ],
    "Médical, Aiguilles & Body Mod": [
        "Medical play",
        "Examens médicaux (roleplay)",
        "Cathéters",
        "Sondes",
        "Lavements",
        "Injections (roleplay)",
        "Aiguilles/Needleplay",
        "Cutting (légère scarification)",
        "Branding",
        "Piercing temporaire",
        "Piercing permanent",
        "Tatouages temporaires",
        "Tatouages permanents",
        "Modification corporelle",
        "Pompage/Pumping",
        "Expansion",
        "Vacuum play"
    ],
    "Restrictions & Contrôle relationnel": [
        "Contrôle de l'alimentation",
        "Contrôle vestimentaire",
        "Contrôle des sorties",
        "Contrôle financier (roleplay)",
        "Contrôle des relations sociales",
        "Contrat BDSM",
        "Règles et protocoles",
        "Suivi/Surveillance",
        "Collier/Symbole de propriété",
        "Cage/Enfermement",
        "Isolation",
        "Sleep deprivation (consensuel)",
        "Jeûne (supervisé)",
        "Restrictions de parole",
        "Forced silence"
    ],
    "Romance & Sensualité": [
        "Câlins",
        "Baisers",
        "Baisers profonds",
        "Massage sensuel",
        "Massage érotique",
        "Caresses",
        "Aftercare intense",
        "Mots doux",
        "Louanges/Praise",
        "Romance classique",
        "Dîner aux chandelles",
        "Eye contact prolongé",
        "Slow sex",
        "Tantrique",
        "Connexion spirituelle",
        "Making love vs. fucking",
        "Sommeil ensemble",
        "Bain ensemble",
        "Se laver mutuellement"
    ],
    "Extrême & Edge Play": [
        "Breath play",
        "Choking",
        "Asphyxiation",
        "Blood play",
        "Knife play",
        "Gun play (jouet)",
        "Fear play",
        "Extreme pain",
        "Suspension",
        "Mummification",
        "Vacuum beds",
        "Intoxication play",
        "Edge play général"
    ],
    "Technologie, Pornographie & Distance": [
        "Sexting",
        "Sexe au téléphone",
        "Sexe par vidéo",
        "Contrôle à distance (jouets)",
        "Porn watching together",
        "Hentai/Anime porn",
        "Audio porn",
        "Literotica",
        "VR porn",
        "Sex robots/dolls",
        "Applications de rencontre",
        "OnlyFans/Contenu adulte",
        "Streaming adulte"
    ],
    "Situations & Contextes": [
        "Sexe matinal",
        "Sexe avant de dormir",
        "Quickie",
        "Sexe marathon",
        "Sexe sous la douche",
        "Sexe dans le bain",
        "Sexe en voiture",
        "Sexe en nature",
        "Sexe à l'hôtel",
        "Sexe au travail (fantaisie)",
        "Sexe pendant les règles",
        "Sexe pendant la grossesse",
        "Sexe avec de la musique",
        "Sexe en silence",
        "Sexe ivre/high",
        "Sexe sobre uniquement"
    ],
    "Communication & Négociation": [
        "Safe words",
        "Check-ins réguliers",
        "Négociation avant",
        "Débriefing après",
        "Communication non-verbale",
        "Signaux",
        "Hard limits respectés",
        "Soft limits explorés",
        "Négociation continue",
        "Consentement enthousiaste",
        "Consentement informed",
        "Discussion des limites",
        "Partage de fantasmes",
        "Journalisation partagée"
    ],
    "Dynamiques D/s & Échange de pouvoir": [
        "Topping sans domination",
        "Bottoming sans soumission",
        "Domination douce/Gentle Dom",
        "Domination sensuelle",
        "Domination de service",
        "Soumission de service",
        "Soumission sexuelle",
        "Soumission domestique",
        "Soumission occasionnelle",
        "Soumission 24/7",
        "Total Power Exchange/TPE",
        "Female-Led Relationship/FLR",
        "Male-Led Relationship/MLR",
        "D/s à distance",
        "D/s non sexuel",
        "Permission pour jouir",
        "Permission pour parler",
        "Permission pour s'asseoir",
        "Dressage/Training",
        "Inspection",
        "Positions de présentation",
        "Marche en laisse",
        "Collier et laisse",
        "Mise aux enchères (roleplay)",
        "Partage avec permission (roleplay)",
        "Free use consensuel"
    ],
    "Bondage & Immobilisation": [
        "Bondage décoratif",
        "Bondage fonctionnel",
        "Bondage improvisé",
        "Bondage avec sangles",
        "Bondage avec film plastique",
        "Bondage avec bandages",
        "Bondage des seins",
        "Bondage génital",
        "Bondage des cuisses",
        "Frogtie",
        "Hogtie",
        "Balltie",
        "Shrimp tie",
        "Futomomo",
        "Box tie",
        "Crotch rope",
        "Predicament bondage",
        "Self-bondage",
        "Bondage sous les vêtements",
        "Immobilisation complète",
        "Spread-eagle",
        "Barre d'écartement",
        "Pilori/Stocks",
        "Camisole de force",
        "Sac de bondage",
        "Cocon de bondage",
        "Suspension partielle",
        "Suspension inversée",
        "Bondage aérien",
        "Évasion/Escape bondage"
    ],
    "Impact Play - Pratiques & Rituels": [
        "Gifles/Slapping",
        "Claques sur les seins",
        "Claques génitales",
        "Bastinado",
        "Ceinture",
        "Règle",
        "Cuillère en bois",
        "Tawse",
        "Dragon tail",
        "Singletail",
        "Bullwhip",
        "Birching",
        "Florentine flogging",
        "Impact rythmique",
        "Impact punitif",
        "Impact sensuel",
        "Impact sur vêtements",
        "Impact à peau nue",
        "Stries de canne",
        "Marques visibles en public",
        "Comptage des coups",
        "Remerciement après chaque coup",
        "Endurance à l'impact",
        "Impact surprise"
    ],
    "Sensations - Textures & Électricité": [
        "Fourrure sur la peau",
        "Soie sur la peau",
        "Jeu avec les ongles",
        "Pincements",
        "Pression corporelle",
        "Étirements",
        "Écrasement léger",
        "Sensations abrasives",
        "Orties/Nettle play",
        "Gingembre/Figging",
        "Menthol",
        "Baume chauffant",
        "Huiles chaudes",
        "Bougies de massage",
        "Cire basse température",
        "Cire colorée",
        "Alternance chaud/froid",
        "Métal froid",
        "Jeu avec la nourriture",
        "Jeu avec des textures",
        "ASMR érotique",
        "Surcharge sensorielle",
        "Casque antibruit",
        "Violet wand",
        "TENS érotique",
        "Électrostimulation génitale",
        "Électrostimulation des tétons",
        "Jeu électrique à distance",
        "Jeu électrique surprise"
    ],
    "Masturbation & Plaisir non pénétratif": [
        "Masturbation solo",
        "Masturbation mutuelle",
        "Regarder son/sa partenaire se masturber",
        "Être regardé(e) en se masturbant",
        "Masturbation guidée",
        "Masturbation commandée",
        "Masturbation avec jouets",
        "Masturbation devant un miroir",
        "Masturbation à distance",
        "Frottement génital/Frottage",
        "Frottement habillé/Dry humping",
        "Grinding",
        "Handjob",
        "Footjob",
        "Thighjob",
        "Breast job/Titjob",
        "Armpit job",
        "Tribadisme/Scissoring",
        "Docking",
        "Intercrural",
        "Stimulation des tétons",
        "Orgasme par stimulation des tétons",
        "Stimulation prostatique",
        "Massage prostatique",
        "Massage de la vulve",
        "Massage du pénis",
        "Massage des testicules",
        "Massage du périnée",
        "Orgasme sans contact génital",
        "Orgasmes multiples",
        "Orgasme simultané",
        "Orgasme sans éjaculation",
        "Éjaculation sans orgasme"
    ],
    "Pratiques orales complémentaires": [
        "Irrumation consensuelle",
        "Face fucking consensuel",
        "Maintien de tête pendant l'oral",
        "Oral mutuel/69",
        "Teabagging",
        "Léchage du corps",
        "Léchage des tétons",
        "Léchage des pieds",
        "Léchage génital prolongé",
        "Déni d'oral",
        "Oral jusqu'à l'orgasme",
        "Oral sans orgasme",
        "Crachat dans la bouche",
        "Échange de salive/Snowballing"
    ],
    "Pénétration - Techniques & Rythmes": [
        "Doigtage vaginal",
        "Doigtage anal",
        "Fingering multiple",
        "Pénétration superficielle",
        "Pénétration profonde",
        "Pénétration lente",
        "Pénétration brutale consensuelle",
        "Pénétration prolongée",
        "Pénétration sans mouvement",
        "Double pénétration vaginale",
        "Double pénétration anale",
        "Triple pénétration",
        "Pénétration simultanée avec jouets",
        "Dilatation vaginale",
        "Dilatation anale",
        "Sounding urétral",
        "Jeu urétral"
    ],
    "Jouets & Machines": [
        "Jouets réalistes",
        "Jouets non réalistes",
        "Jouets gonflables",
        "Jouets texturés",
        "Jouets rotatifs",
        "Machines sexuelles",
        "Fucking machine",
        "Sybian",
        "Tentacules artificiels",
        "Godemiché double",
        "Gode creux",
        "Extenseur pénien",
        "Gaine pénienne",
        "Cock ring",
        "Anneau vibrant",
        "Masturbateur",
        "Fleshlight",
        "Œuf masturbateur",
        "Poupée sexuelle",
        "Moulage génital personnalisé",
        "Jouets portés en public",
        "Plug porté longtemps",
        "Plug avec queue",
        "Plug gonflable",
        "Plug tunnel",
        "Tunnel anal"
    ],
    "Orgasme, Edging & Chasteté": [
        "Edging prolongé",
        "Edging répétitif",
        "Déni ponctuel",
        "Déni prolongé",
        "Déni permanent (fantasme)",
        "Orgasme sur permission",
        "Orgasme sur commande",
        "Compte à rebours avant orgasme",
        "Orgasme interrompu",
        "Orgasmes forcés multiples",
        "Surstimulation après orgasme",
        "Masturbation imposée",
        "Abstinence imposée",
        "Chasteté masculine",
        "Chasteté féminine",
        "Chasteté à distance",
        "Détention de clé/Keyholding",
        "Port prolongé d'une cage",
        "Port public discret d'une cage",
        "Tease and denial",
        "Cum control",
        "Cum Eating Instruction/CEI"
    ],
    "Jeux génitaux": [
        "Cock and Ball Torture/CBT",
        "Pussy torture",
        "Ballbusting",
        "Ball stretching",
        "Ball weights",
        "Cock stepping",
        "Écrasement génital",
        "Pinces génitales",
        "Corde génitale",
        "Wax play génital",
        "Température génitale",
        "Bondage du pénis",
        "Bondage des testicules",
        "Bondage de la vulve",
        "Humiliation génitale",
        "Small Penis Humiliation/SPH",
        "Adoration du pénis",
        "Adoration de la vulve",
        "Adoration des fesses",
        "Adoration des seins"
    ],
    "Messy Play & Fluides complémentaires": [
        "Cum play",
        "Cum marking",
        "Cum swapping",
        "Creampie vaginal",
        "Creampie anal",
        "Creampie oral",
        "Éjaculation dans les cheveux",
        "Éjaculation sur les vêtements",
        "Éjaculation multiple",
        "Bave/Drooling",
        "Larmes",
        "Jeu avec huiles",
        "Jeu avec lubrifiant",
        "Jeu avec boue",
        "Messy play",
        "Sploshing/WAM",
        "Nourriture sur le corps",
        "Bains de liquide",
        "Urophagie",
        "Vomit play/Émétophilie"
    ],
    "Exhibition & Médias": [
        "Exhibition consensuelle privée",
        "Exhibition devant un groupe consentant",
        "Exhibition en ligne",
        "Nudité à domicile",
        "Nudité semi-publique",
        "Risque d'être découvert (sans tiers impliqué)",
        "Voyeurisme consensuel",
        "Partenaire regardant une relation",
        "Miroirs pendant le sexe",
        "Se filmer",
        "Regarder ses propres vidéos",
        "Photographie érotique",
        "Modèle pour photographie érotique",
        "Réaliser du contenu pour adulte",
        "Mise en scène pornographique",
        "Cam show privé",
        "Cam show public",
        "Sextape",
        "Diffusion en direct consentie",
        "Masque ou anonymat dans le contenu"
    ],
    "Non-monogamie, Échangisme & Groupe": [
        "Quatuor",
        "Reverse gang bang",
        "Double équipe/Double teaming",
        "Train",
        "Cercle de masturbation",
        "Sexe en groupe",
        "Soft swap",
        "Full swap",
        "Couple avec personne invitée",
        "Unicorn/Troisième partenaire",
        "Cuckqueaning",
        "Stag and vixen",
        "Compersion",
        "Polyfidélité",
        "Anarchie relationnelle",
        "Partage d'un partenaire dominant",
        "Partage d'un partenaire soumis",
        "Usage collectif consensuel"
    ],
    "Roleplay - Fantastique & Scénarios": [
        "Domestique/Majordome",
        "Prisonnier/Gardien",
        "Royalité/Serviteur",
        "Célébrité/Fan",
        "Inconnu(e)s",
        "Première rencontre",
        "Escort/Client",
        "Stripteaseur/Client",
        "Photographe/Modèle",
        "Coach/Athlète",
        "Masseur/Client",
        "Vampire",
        "Démon/Succube/Incube",
        "Ange",
        "Divinité/Adorateur",
        "Sorcier/Sorcière",
        "Super-héros/Vilain",
        "Robot/IA",
        "Poupée vivante",
        "Mannequin/Statue",
        "Marionnette",
        "Transformation magique",
        "Changement de genre (fantasme)",
        "Body swap",
        "Clone/Doppelgänger",
        "Géant/Miniature (fantasme)",
        "Dollification",
        "Bimbofication",
        "Himboification",
        "Corruption entre adultes (fantasme)",
        "Somnophilie consensuelle simulée",
        "Capture et évasion (roleplay)",
        "Cambriolage (roleplay)",
        "Marché aux esclaves (roleplay adulte)"
    ],
    "Furry & Creature Play": [
        "Furry fandom",
        "Fursona",
        "Fursuit",
        "Partial fursuit",
        "Fursuit sex/Murrsuiting",
        "Furry roleplay",
        "Yiff",
        "Art furry érotique",
        "Furry virtuel/Avatar",
        "Transformation en furry (fantasme)",
        "Anthropomorphisme",
        "Kemonomimi",
        "Neko/Catgirl/Catboy adulte",
        "Monster play",
        "Creature play",
        "Tentacle play",
        "Alien play",
        "Dragon play",
        "Werewolf play",
        "Oviposition (fantasme)",
        "Breeding kink (fantasme)",
        "Size difference fantasy",
        "Macro/Micro furry",
        "Vore (fantasme)",
        "Transformation corporelle furry"
    ],
    "Pet Play": [
        "Pet play non sexuel",
        "Pet play sexuel",
        "Owner/Pet",
        "Handler/Pet",
        "Dog play",
        "Cat play",
        "Fox play",
        "Bunny play",
        "Cow play",
        "Pig play",
        "Animal transformation (fantasme)",
        "Dressage d'animal",
        "Gamelles",
        "Cage pour pet",
        "Collier pour pet",
        "Tours et commandes",
        "Récompenses pour pet",
        "Concours/Exposition de pet",
        "Pet humiliation",
        "Pet praise",
        "Pet space"
    ],
    "ABDL & Ageplay adulte": [
        "ABDL",
        "Adult Baby/AB",
        "Diaper Lover/DL",
        "Age regression volontaire entre adultes",
        "Ageplay non sexuel entre adultes",
        "Ageplay sexuel entre adultes",
        "Caregiver/Little entre adultes",
        "Mommy/Little entre adultes",
        "Daddy/Little entre adultes",
        "Big/Little entre adultes",
        "Nursery roleplay entre adultes",
        "Nurserie/Chambre de bébé adulte",
        "Couches adultes",
        "Port occasionnel de couches adultes",
        "Port permanent de couches adultes",
        "Couches sous les vêtements",
        "Couches en public de façon discrète",
        "Couches en tissu",
        "Couches jetables",
        "Couches épaisses/Bulky diapers",
        "Couches décorées",
        "Changement de couche adulte",
        "Être changé(e) comme un bébé adulte",
        "Changer la couche d'un adulte",
        "Vérification de couche adulte",
        "Poudre et crème pour change",
        "Wet diaper play adulte",
        "Messy diaper play adulte",
        "Omorashi avec couche adulte",
        "Mouillage volontaire de couche adulte",
        "Usage fonctionnel des couches adultes",
        "Humiliation liée aux couches adultes",
        "Praise liée aux couches adultes",
        "Punition par les couches adultes",
        "Dépendance aux couches (fantasme adulte)",
        "Réapprentissage de la propreté (roleplay adulte)",
        "Accidents simulés entre adultes",
        "Biberon adulte",
        "Tétine adulte",
        "Grenouillère adulte/Onesie",
        "Body bébé taille adulte",
        "Vêtements enfantins taille adulte",
        "Bavoir adulte",
        "Doudou/Peluche",
        "Lit à barreaux taille adulte",
        "Table à langer taille adulte",
        "Chaise haute taille adulte",
        "Poussette taille adulte",
        "Jeux et coloriages en little space",
        "Histoires au coucher en little space",
        "Sieste imposée en ageplay adulte",
        "Heure du coucher en ageplay adulte",
        "Règles de caregiver/little",
        "Récompenses en caregiver/little",
        "Discipline en ageplay adulte",
        "Little space",
        "Middle space",
        "Baby space adulte",
        "Réconfort et nurturing ageplay",
        "Régression à distance entre adultes",
        "ABDL en couple",
        "ABDL en groupe d'adultes"
    ],
    "Corps & Apparence": [
        "Seins",
        "Tétons",
        "Fesses",
        "Pénis",
        "Vulve",
        "Testicules",
        "Anus",
        "Ventre",
        "Nombril",
        "Cuisses",
        "Jambes",
        "Mains",
        "Doigts",
        "Cou",
        "Dos",
        "Visage",
        "Lèvres",
        "Langue",
        "Dents",
        "Voix",
        "Barbe/Moustache",
        "Crâne rasé",
        "Corpulence forte",
        "Corpulence mince",
        "Grande taille",
        "Petite taille",
        "Différence de taille",
        "Différence de musculature",
        "Cicatrices",
        "Vergetures",
        "Taches de rousseur",
        "Marques de bronzage",
        "Corps huilé",
        "Corps mouillé",
        "Grossesse (adulte)"
    ],
    "Vêtements & Matières": [
        "Jeans/Denim",
        "Costumes",
        "Chemises",
        "Cravates",
        "Jupes",
        "Robes",
        "Mini-jupes",
        "Uniforme scolaire (roleplay adulte)",
        "Uniforme de bureau",
        "Uniforme de pompier",
        "Uniforme sportif",
        "Tenue de soubrette",
        "Vêtements mouillés",
        "Vêtements déchirés",
        "Sous-vêtements portés",
        "Vêtements du/de la partenaire",
        "Nudité sous les vêtements",
        "Sans sous-vêtements",
        "Tenue imposée",
        "Tenue transparente",
        "Combinaison intégrale",
        "Zentai",
        "Catsuit",
        "Latex sous vide",
        "Néoprène",
        "Vinyle",
        "Dentelle",
        "Chaussettes",
        "Chaussures de sport",
        "Pieds nus",
        "Cuissardes"
    ],
    "Masques & Anonymat": [
        "Cagoule",
        "Hood en cuir",
        "Hood en latex",
        "Masque intégral",
        "Masque à gaz",
        "Masque médical",
        "Masque animal",
        "Masque vénitien",
        "Anonymat complet",
        "Partenaire masqué(e)",
        "Ne pas voir son/sa partenaire",
        "Être vu(e) sans voir",
        "Groupe de personnes masquées",
        "Dépersonnalisation par le masque"
    ],
    "Humiliation & Adoration corporelle": [
        "Praise kink",
        "Dégradation affectueuse",
        "Humiliation corporelle",
        "Humiliation sexuelle",
        "Humiliation de performance",
        "Humiliation par comparaison",
        "Humiliation devant un miroir",
        "Humiliation enregistrée",
        "Supplication/Begging",
        "Ramper",
        "Position à genoux",
        "Crachat humiliant",
        "Usage comme repose-pieds",
        "Usage comme siège",
        "Body writing",
        "Écriture d'insultes sur le corps",
        "Marquage temporaire",
        "Boot worship",
        "Ass worship",
        "Breast worship",
        "Genital worship",
        "Muscle worship"
    ],
    "Contrôle quotidien & Discipline": [
        "Contrôle du sommeil",
        "Heure de coucher imposée",
        "Contrôle de la masturbation",
        "Contrôle de la pornographie",
        "Contrôle du téléphone",
        "Contrôle du temps d'écran",
        "Contrôle de la posture",
        "Contrôle du langage",
        "Contrôle des toilettes",
        "Contrôle de l'hygiène",
        "Contrôle de l'apparence",
        "Contrôle des sous-vêtements",
        "Contrôle des jouets",
        "Contrôle de la nudité",
        "Rédaction de lignes",
        "Coin de punition",
        "Time-out",
        "Corvées",
        "Rapport quotidien",
        "Demande d'autorisation",
        "Emploi du temps imposé",
        "Système de points",
        "Tableau de récompenses",
        "Récompenses sexuelles",
        "Privation de privilèges",
        "Dress code",
        "Inspection quotidienne",
        "Preuve photographique consensuelle",
        "Géolocalisation consensuelle",
        "Findom",
        "Cashmaster/Cashslave",
        "Human ATM (roleplay)"
    ],
    "Fear Play & Intimidation": [
        "Menaces fictives",
        "Intimidation",
        "Poursuite",
        "Jeu dans l'obscurité",
        "Inconnu(e) simulé(e)",
        "Menace d'exposition fictive",
        "Blackmail consensuel avec limites",
        "Jeu de survie simulé",
        "Interrogatoire intense",
        "Couteau émoussé",
        "Mise en scène médicale effrayante",
        "Claustrophobie contrôlée",
        "Enfermement dans un petit espace",
        "Jeu avec la hauteur",
        "Chute simulée",
        "Compte à rebours",
        "Incertitude sensorielle",
        "Abandon (fantasme)"
    ],
    "Médical - Examens & Hôpital": [
        "Jeu d'hôpital",
        "Opération simulée",
        "Dentiste (roleplay)",
        "Gynécologue (roleplay)",
        "Urologue (roleplay)",
        "Examen rectal",
        "Examen vaginal",
        "Examen génital",
        "Prise de température",
        "Stéthoscope",
        "Gants médicaux",
        "Table d'examen",
        "Étriers médicaux",
        "Bandages médicaux",
        "Plâtres",
        "Immobilisation médicale",
        "Fausses injections",
        "Prise de sang simulée",
        "Suture simulée",
        "Clamps médicaux",
        "Patient inconscient simulé"
    ],
    "Intimité & Aftercare": [
        "Spooning",
        "Se tenir la main",
        "Contact peau à peau",
        "Dormir nu ensemble",
        "Douche mutuelle",
        "Se déshabiller lentement",
        "Habiller son/sa partenaire",
        "Striptease",
        "Lap dance",
        "Danse érotique",
        "Lecture érotique",
        "Jeu de séduction",
        "Flirt prolongé",
        "Sexe ludique",
        "Rires pendant le sexe",
        "Aftercare physique",
        "Aftercare verbal",
        "Aftercare à distance",
        "Aftercare différé",
        "Aftercare minimal",
        "Pas d'aftercare souhaité",
        "Gestion du subdrop",
        "Gestion du domdrop",
        "Check-in le lendemain"
    ],
    "Technologie interactive & Connectée": [
        "Jouet connecté",
        "Contrôle aléatoire d'un jouet",
        "Contrôle d'un jouet par musique",
        "Contrôle d'un jouet par pourboires",
        "Contrôle d'un jouet par plusieurs partenaires",
        "Jeu de rôle par texte",
        "Jeu de rôle vocal",
        "Jeu de rôle vidéo",
        "Hypnose audio",
        "Instructions audio enregistrées",
        "Messages programmés",
        "Tâches envoyées à distance",
        "Preuves photo/vidéo consenties",
        "Chatbot érotique",
        "Compagnon virtuel",
        "Avatar érotique",
        "Métavers érotique",
        "Teledildonics",
        "Pornographie interactive",
        "Jeu vidéo érotique",
        "Deepfake consensuel de soi"
    ],
    "Consentement & Sécurité pratique": [
        "Safeword verbal",
        "Safeword non verbal",
        "Système vert/orange/rouge",
        "Tap out",
        "Objet lâché comme signal",
        "Consentement spécifique à chaque pratique",
        "Consentement global pour une scène",
        "Consentement préalable durable",
        "Limites temporaires",
        "Limites selon le partenaire",
        "Limites selon le contexte",
        "Liste Oui/Non/Peut-être",
        "Négociation écrite",
        "Négociation orale",
        "Contrat symbolique",
        "Contrat détaillé",
        "Discussion de santé sexuelle",
        "Tests IST",
        "Préservatifs",
        "Digues dentaires",
        "Gants de protection",
        "Fluid bonding",
        "Plan de sécurité",
        "Contact d'urgence",
        "Vérification émotionnelle",
        "Vérification de la circulation",
        "Débrief immédiat",
        "Débrief différé",
        "Feedback écrit",
        "Photos uniquement avec permission",
        "Interdiction d'enregistrement",
        "Confidentialité de la scène",
        "Pas de marques visibles",
        "Marques visibles acceptées",
        "Zones interdites aux marques"
    ]
};
